yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('posts/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/', views.profile_follow,
         name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow,
         name='profile_unfollow'),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import constraints

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст',
                            help_text='Введите текст поста')
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(Group, on_delete=models.SET_NULL, blank=True,
                              null=True, related_name='posts',
                              verbose_name='Группа',
                              help_text='Выберите группу')
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, blank=True,
                             null=True, related_name='comments',
                             verbose_name='Статья')
    author = models.ForeignKey(User, on_delete=models.CASCADE, blank=True,
                               null=True, related_name='comments',
                               verbose_name='Автор статьи')
    text = models.TextField('Текст', help_text='Текст комментария')
    created = models.DateTimeField('Дата и время публикации',
                                   auto_now_add=True)

    class Meta:
        ordering = ['post']
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='follower'
                             )
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='following'
                               )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = [constraints.UniqueConstraint(fields=['user', 'author'],
                                                    name='unique_following')]

yatube/posts/forms.py
from django import forms

from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post


def pages_pagination(request, s):
    paginate_by = int(settings.PAGINATE_BY)
    paginator = Paginator(s, paginate_by)
    page_num = request.GET.get('page')
    page_obj = paginator.get_page(page_num)
    return page_obj


def index(request):
    post_list = Post.objects.all()
    page_obj = pages_pagination(request, post_list)
    template = 'posts/index.html'
    context = {
        'page_obj': page_obj,
    }
    return render(request, template, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = pages_pagination(request, posts)
    template = 'posts/group_list.html'
    context = {
        'posts': posts,
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    total_author_posts = author.posts.all()
    page_obj = pages_pagination(request, total_author_posts)
    user = request.user
    following = user.is_authenticated and author.following.exists()
    context = {
        'author': author,
        'page_obj': page_obj,
        'following': following,
    }

    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    context = {
        'post': post,
        'form': form,
        'comments': post.comments.all(),
        'post_id': post_id,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author.username)
    return render(request, 'posts/post_create.html', {'form': form})


@login_required
def post_edit(request, post_id):
    edit_post = get_object_or_404(Post, pk=post_id)
    form = PostForm(request.POST or None, files=request.FILES or None,
                    instance=edit_post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    return render(request, 'posts/post_create.html',
                  {'edit_post': True, 'form': form})


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    """
    Информация о текущем пользователе доступна в переменной request.user.
    Находит посты, у которых автор связан через модель Follow
    с текущим пользователем.
    """
    posts = Post.objects.filter(author__following__user=request.user)
    page_obj = pages_pagination(request, posts)
    context = {
        'posts': posts,
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """Подписаться на автора."""
    user = request.user
    author = get_object_or_404(User, username=username)
    if user != author:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    """Отписаться от автора."""
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  Последние обновления на сайте
{% endblock %}

{% block content %}
{% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    <ul>
      <li>
        Автор:<a href="{% url 'posts:profile' username=post.author.username %}">
          {{ post.author.get_full_name }}
        </a>
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "800x300" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
        {% if request.user == post.author %}
          <a href="{% url 'posts:post_edit' post.id %}">Редактировать запись</a><br>
        {% endif %}
        <a href="{% url 'posts:post_detail' post.pk %}">Подробная информация </a><br>
        {% if post.group %}
          <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
 Записи сообщества {{ group }}
{% endblock %}

{% block content %}
  <h1>{{ group }}</h1>
  <p>{{ group.description }}</p>
    {% for post in page_obj %}
      <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
       </ul>
       {% thumbnail post.image "960x339" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
       {% endthumbnail %}    
        <p>{{ post.text }}</p>         
      {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}

{% block title %}
  Последние обновления
{% endblock %}

{% block content %}
{% cache 20 index_page %}
{% include 'posts/includes/switcher.html' %}
{% for post in page_obj %}
  <ul>
    <li>
      Автор: {{ post.author.get_full_name }}
    </li>
    <li>
      Дата публикации: {{ post.pub_date|date:"d E Y" }}
    </li>
  </ul>
  <p>{{ post.text }}</p>
  {% thumbnail post.image "800x300" upscale=True as im %}
    <img class="card-img my-2" src="{{ im.url }}">
  {% endthumbnail %}
  <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a><br>
  {% if post.group %}    
  <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
  {% endif %}
  <hr>
{% endfor %}
{% endcache %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/post_create.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}
  {% if edit_post %}
    Редактировать
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}

{% block content %}
<div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                {% if edit_post %} 
                  Редактировать
                {% else %}
                  Новый пост
                {% endif %}           
              </div>
              <div class="card-body">  
              {% if field.errors %}
                  <div class="alert alert-danger" role="alert">
                      {{ field.error }}
                  </div>
                {% endif %} 
                <form method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                     
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                       {{ form.text.label }}           
                      <span class="required text-danger" >*</span>                  
                    </label>
                    
                    {{ form.text }}                
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                                        
                    </label>
                    {{ form.group.label }}
                    {{ form.group }}
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div>
                      Картинка<br> 
                      <label>                 
                    {{ form.image }}
                    </label>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                    {% if edit_post %}
                      Сохранить
                    {% else %}
                      Добавить
                    {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}

{% block title %}
  Пост {{ post.text|truncatechars:30 }}
{% endblock %}

{% block content %}
<div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
            <!-- если у поста есть группа -->
            {% if post.group %}   
              <li class="list-group-item">
                Группа: {{ post.group }}<br>
                <a href="{% url 'posts:group_list' post.group.slug %}">
                  все записи группы
                </a>
              </li>
            {% endif %}
              <li class="list-group-item">
                Автор: {{ post.author.get_full_name }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post.author.posts.count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "800x300" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
           {{ post.text }} 
          </p>
          {% if user == post.author %}
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
              редактировать запись
            </a>
          {% endif %}
          
          {% include 'posts/includes/comments.html' %}

        </article>
      </div> 
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load user_filters %}

{% block title %}
  Профайл пользователя {{ author.get_full_name }}
{% endblock %}

{% block content %}
<h1>Все посты пользователя {{ author.get_full_name }} </h1>
<h3>Всего постов: {{ author.posts.count }} </h3>
{% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
   {% endif %}
</div>
{% for post in page_obj %}  
        <article>
          <ul>
            <li>
              Автор: {{ author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
          </ul>
          {% thumbnail post.image "960x339" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
          {{ post.text }} 
          </p>
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
        </article>
        {% if post.group %}      
        <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
{% endblock %}